# Generated by Django 4.0.1 on 2022-01-29 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('code', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('pseudonyme', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pseudonymePerso', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField(default=False)),
                ('refFamily', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.family')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stockage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('dureConservation', models.CharField(max_length=30)),
                ('refFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.family')),
            ],
            options={
                'unique_together': {('nom', 'refFamily')},
            },
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('refFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.family')),
            ],
            options={
                'unique_together': {('nom', 'refFamily')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('dureConservation', models.CharField(max_length=30)),
                ('refFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.family')),
            ],
            options={
                'unique_together': {('nom', 'refFamily')},
            },
        ),
    ]
