# Generated by Django 4.0.1 on 2022-06-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('dureConservation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('code', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Tâche', 'Tâche'), ('Course', 'Course')], max_length=30)),
                ('refFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.family')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('isCheck', models.BooleanField(default=False)),
                ('refListe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.liste')),
            ],
        ),
        migrations.CreateModel(
            name='Stockage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('dureConservation', models.IntegerField()),
                ('refFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.family')),
            ],
            options={
                'unique_together': {('nom', 'refFamily')},
            },
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('refFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.family')),
            ],
            options={
                'unique_together': {('nom', 'refFamily')},
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('quantityMin', models.IntegerField(null=True)),
                ('isQuantityMin', models.BooleanField(default=False)),
                ('quantityAutoAdd', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mesure', models.CharField(default='pièce', max_length=30)),
                ('notifPeremption', models.IntegerField(default=2)),
                ('refCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.category')),
                ('refStockage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.stockage')),
            ],
        ),
        migrations.CreateModel(
            name='PeremptionProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePeremption', models.DateField()),
                ('quantity', models.IntegerField()),
                ('notifPeremption', models.IntegerField(default=2)),
                ('refProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('refFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.family')),
                ('refPeremption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.peremptionproduit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesure', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('refProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
                ('refRepas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.repas')),
            ],
        ),
        migrations.CreateModel(
            name='LigneListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesure', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('isCheck', models.BooleanField(default=False)),
                ('autoAdd', models.BooleanField(default=False)),
                ('nomProdOptional', models.CharField(blank=True, max_length=30, null=True)),
                ('refListe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.liste')),
                ('refProduit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='refFamily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.family'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('pseudonyme', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pseudonymePerso', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField(default=False)),
                ('refFamily', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.family')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('nom', 'refFamily')},
        ),
    ]
