# Generated by Django 4.0.1 on 2022-02-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('quantityMin', models.IntegerField()),
                ('isQuantityMin', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('refStockage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stockage')),
            ],
        ),
    ]
