# Generated by Django 4.0.1 on 2022-01-26 15:57

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='code',
            field=models.TextField(default=myapp.models.get_random_code),
        ),
    ]
