# Generated by Django 4.0.1 on 2022-01-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_family_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('pseudonyme', models.CharField(max_length=30, unique=True)),
                ('pseudonymePerso', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('refFamily', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.family')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
