# Generated by Django 4.0.1 on 2022-02-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_liste_tache_alter_produit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='refFamily',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='refListe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.liste'),
            preserve_default=False,
        ),
    ]
