# Generated by Django 4.0.1 on 2022-04-13 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_liste_reffamily_tache_refliste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste',
            name='category',
            field=models.CharField(choices=[('Tâche', 'Tâche'), ('Course', 'Course')], max_length=30),
        ),
        migrations.CreateModel(
            name='PeremptionProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePeremption', models.DateField()),
                ('notifPeremption', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('refProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesure', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('refProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
                ('refRepas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.repas')),
            ],
        ),
        migrations.CreateModel(
            name='LigneListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesure', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('isCheck', models.BooleanField(default=False)),
                ('autoAdd', models.BooleanField(default=False)),
                ('autoAddQuantity', models.IntegerField()),
                ('refListe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.liste')),
                ('refProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
    ]
