# Generated by Django 4.0.1 on 2022-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_liste_category_peremptionproduit_lignerepas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneliste',
            name='autoAddQuantity',
        ),
        migrations.AddField(
            model_name='produit',
            name='quantityAutoAdd',
            field=models.IntegerField(null=True),
        ),
    ]
