# Generated by Django 4.0.1 on 2022-04-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_ligneliste_autoaddquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='quantityAutoAdd',
            field=models.IntegerField(default=0),
        ),
    ]
