# Generated by Django 4.0.1 on 2022-05-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_produit_quantityautoadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='refCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
            preserve_default=False,
        ),
    ]
