# Generated by Django 4.0.1 on 2022-05-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_produit_refcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneliste',
            name='test',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ligneliste',
            name='refProduit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.produit'),
        ),
    ]
