# Generated by Django 4.0.1 on 2022-05-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_ligneliste_test_alter_ligneliste_refproduit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ligneliste',
            old_name='test',
            new_name='nomProdOptional',
        ),
        migrations.AlterField(
            model_name='produit',
            name='refCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='refStockage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.stockage'),
        ),
    ]
