# Generated by Django 4.0.1 on 2022-06-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_test_ligneliste_nomprodoptional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peremptionproduit',
            name='notifPeremption',
        ),
        migrations.AlterField(
            model_name='category',
            name='dureConservation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='refCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='stockage',
            name='dureConservation',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('refFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.family')),
                ('refPeremption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.peremptionproduit')),
            ],
        ),
    ]
