# Generated by Django 4.0.1 on 2022-06-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_peremptionproduit_notifperemption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='mesure',
            field=models.CharField(default='pièce', max_length=30),
        ),
    ]
