# Generated by Django 4.0.1 on 2022-06-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_produit_quantityautoadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='peremptionproduit',
            name='notifPeremption',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='produit',
            name='notifPeremption',
            field=models.IntegerField(default=2),
        ),
    ]
